#!/usr/bin/env python
import requests,sys
if sys.argv[1] == "-h":
	print "File34 -h"
	print "File34 [website] [page list] [result location]"
	exit()
else:
	website = sys.argv[1]
	filep = sys.argv[2]
	final = sys.argv[3]
codes = []
file = open(filep, "r")
for line in file:
	r = requests.get('{}{}'.format(website, line.rstrip()))
	codes.append("{} : {} ".format(line, r.status_code))
	print "{} : {} ".format(line, r.status_code)	
print codes
file.close()
file = open(final, "w")
file.write(website)
for vals in codes:
	file.write(vals+"\n")
file.close()
